version: '3'
services:
  web:
    image: "modx:${MODX_VERSION}"
    build: 
      context: ./apache
      args:
        - MODX_VERSION
        - MODX_SHA1
    container_name: modx
    depends_on:
      - db
    ports:
      - '8000:80'
    environment:
      MODX_VERSION: "${MODX_VERSION}"
      MODX_DB_HOST: "${MODX_DB_HOST}"
      MODX_DB_PASSWORD: "${MODX_DB_PASSWORD}"
      MODX_DB_USER: "${MODX_DB_USER}"
      MODX_DB_NAME: "${MODX_DB_NAME}"
    volumes:
      - './html:/var/www/html'
  db:
    image: mysql:8.0.28-oracle
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MODX_DB_NAME}"
      MYSQL_USER: "${MODX_DB_USER}"
      MYSQL_PASSWORD: "${MODX_DB_PASSWORD}"
    ports:
      - '3306:3306'
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    volumes:
      - './mysql:/var/lib/mysql'
    user: mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
    restart: always
    ports:
      - 8001:80
    volumes:
      - /sessions
