version: '3'
services:
  web:
    image: modx
    build: ./apache
    container_name: modx
    depends_on:
      - db
    ports:
      - '8000:80'
    environment:
      MODX_VERSION: 3.0.0
      MODX_DB_HOST: db:3306
      MODX_DB_PASSWORD: modx
      MODX_DB_USER: modx
      MODX_DB_NAME: modx
    volumes:
      - './html:/var/www/html'
  db:
    image: mysql:8.0.28-oracle
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: modx
      MYSQL_USER: modx
      MYSQL_PASSWORD: modx
    ports:
      - '3306:3306'
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    volumes:
      - './mysql:/var/lib/mysql'
    user: mysql
